export const cardsData = [
  {
    id: 1,
    img: "images/Chrono Classic Watch.png",
    product: "Chrono Classic Watch",
    price: "$250",
    category: "Watches",
    favorite: false,
  },
  {
    id: 2,
    img: "images/Noir Leather Watch.png",
    product: "Noir Leather Watch",
    price: "$180",
    category: "Watches",
    favorite: false,
  },
  {
    id: 3,
    img: "images/Silver Edge Watch.png",
    product: "Silver Edge Watch",
    price: "$300",
    category: "Watches",
    favorite: false,
  },
  {
    id: 4,
    img: "images/Minimal Steel Watch.png",
    product: "Minimal Steel Watch",
    price: "$220",
    category: "Watches",
    favorite: false,
  },
  {
    id: 5,
    img: "images/Oud Royale.png",
    product: "Oud Royale",
    price: "$220",
    category: "Perfumes",
    favorite: false,
  },
  {
    id: 6,
    img: "images/Bracelets.png",
    product: "Silver Bracelets",
    price: "$80",
    category: "Jewelry",
    favorite: false,
  },
  {
    id: 7,
    img: "images/Black Bracelets.png",
    product: "Black Bracelets",
    price: "$65",
    category: "Jewelry",
    favorite: false,
  },
  {
    id: 8,
    img: "images/Necklaces.png",
    product: "Necklaces",
    price: "$350",
    category: "Jewelry",
    favorite: false,
  },
  {
    id: 9,
    img: "images/Rings.png",
    product: "Rings",
    price: "$400",
    category: "Jewelry",
    favorite: false,
  },
];
